---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  workspaces:
  - name: source
  tasks:
  - name: clone
    taskRef:
      name: git
    workspaces:
    - name: source
      workspace: source
    params:
    - name: repository
      value: https://github.com/leandroberetta/hello
    - name: revision
      value: master
  - name: package
    taskRef:
      name: mvn
    runAfter:
    - clone
    workspaces:
    - name: source
      workspace: source
    params:
    - name: command
      value: package
  - name: build
    taskRef:
      name: buildah
    runAfter:
    - package
    workspaces:
    - name: source
      workspace: source
    params:
    - name: image
      value: quay.io/leandroberetta/hello
  - name: deploy
    taskRef:
      name: kubectl
    runAfter:
    - build
    workspaces:
    - name: source
      workspace: source
    params:
    - name: command
      value: apply -f $(workspaces.source.path)/hello.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: quay-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-bot-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: build-bot
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-pipeline-run
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: hello-pipeline
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: source