apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mvn
spec:
  workspaces:
    - name: source
  params:
    - name: COMMAND
    - name: CONTEXT_PATH
      default: .
  steps:
    - name: mvn
      image: quay.io/karpenter/mvn
      workingdir: $(workspaces.source.path)
      script: |
        mvn $(params.COMMAND) -f $(params.CONTEXT_PATH)
