apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s2i
spec:
  params:
    - name: BASE_IMAGE
    - name: BASE_IMAGE_S2I_SCRIPTS
      default: /usr/libexec/s2i
    - name: IMAGE
    - name: TLS_VERIFY
      default: "true"
    - name: CONTEXT_PATH
      default: .
    - name: FORMAT
      default: oci
    - name: INCREMENTAL
      default: "false"
  workspaces:
    - name: source
  steps:
    - name: generate
      image: quay.io/karpenter/s2i
      script: |
        s2i build $(workspaces.source.path)/$(params.CONTEXT_PATH) $(params.BASE_IMAGE) $(params.IMAGE) --incremental=$(params.INCREMENTAL) --image-scripts-url=image://$(params.BASE_IMAGE_S2I_SCRIPTS) --as-dockerfile /source-to-image/Dockerfile
      volumeMounts:
        - name: source-to-image
          mountPath: /source-to-image
    - name: build
      image: quay.io/karpenter/buildah
      workingDir: /source-to-image
      script: |                
        buildah bud --no-cache --format=$(params.FORMAT) --tls-verify=$(params.TLS_VERIFY) -f Dockerfile -t $(params.IMAGE)
      volumeMounts:
        - name: containers
          mountPath: /var/lib/containers
        - name: source-to-image
          mountPath: /source-to-image
      securityContext:
        privileged: true
    - name: push
      image: quay.io/karpenter/buildah
      workingDir: $(workspaces.source.path)
      script: |
        buildah push --tls-verify=$(params.TLS_VERIFY) $(params.IMAGE) docker://$(params.IMAGE)
      volumeMounts:
        - name: containers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: containers
      emptyDir: {}
    - name: source-to-image
      emptyDir: {}