apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s2i
spec:
  params:
    - name: BASE_IMAGE
    - name: IMAGE
    - name: TLS_VERIFY
      default: "true"
    - name: CONTEXT_PATH
      default: .
    - name: FORMAT
      default: oci
  workspaces:
    - name: source
  steps:
    - name: generate
      image: quay.io/karpenter/s2i
      script: |
        s2i build $(workspaces.source.path) $(params.BASE_IMAGE) --as-dockerfile /dockerfile/Dockerfile
      volumeMounts:
        - name: dockerfile
          mountPath: /dockerfile
    - name: build
      image: quay.io/karpenter/buildah
      workingDir: $(workspaces.source.path)
      script: |                
        buildah bud --no-cache --format=$(params.FORMAT) --tls-verify=$(params.TLS_VERIFY) -f /dockerfile/Dockerfile -t $(params.IMAGE) $(params.CONTEXT_PATH)
      volumeMounts:
        - name: containers
          mountPath: /var/lib/containers
        - name: dockerfile
          mountPath: /dockerfile
      securityContext:
        privileged: true
    - name: push
      image: quay.io/karpenter/buildah
      workingDir: $(workspaces.source.path)
      script: |
        buildah push --tls-verify=$(params.TLS_VERIFY) $(params.IMAGE) docker://$(params.IMAGE)
      volumeMounts:
        - name: containers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: containers
      emptyDir: {}
    - name: dockerfile
      emptyDir: {}