apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-apply
spec:
  workspaces:
  - name: source
  params:
  - name: file
    description: File containing the resources to apply
  steps:
  - name: apply
    image: quay.io/karpenter/kubectl
    script: |      
      kubectl apply -f $(workspaces.source.path)/${params.file}