apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: example.org/hello/hello:latest
        imagePullPolicy: Always
        name: hello
        env:
        - name: HELLO_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: hello
              key: HELLO_MESSAGE
        ports:        
        - containerPort: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 256Mi
            cpu: 200m