apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  workspaces:
  - name: source
  tasks:
  - name: clone
    taskRef:
      name: git
    workspaces:
    - name: source
      workspace: source
    params:
    - name: REPOSITORY
      value: https://github.com/leandroberetta/karpenter
    - name: REVISION
      value: master
  - name: package
    taskRef:
      name: mvn
    runAfter:
    - clone
    workspaces:
    - name: source
      workspace: source
    params:
    - name: COMMAND
      value: package
    - name: CONTEXT_PATH
      value: demo/app
  - name: build
    taskRef:
      name: buildah
    runAfter:
    - package
    workspaces:
    - name: source
      workspace: source
    params:
    - name: IMAGE
      value: example.org:80/hello/hello:latest
    - name: CONTEXT_PATH
      value: demo/app
    - name: TLS_VERIFY
      value: "false"
    - name: FORMAT
      value: docker
  - name: deploy
    taskRef:
      name: kubectl
    runAfter:
    - build
    workspaces:
    - name: source
      workspace: source
    params:
    - name: COMMAND
      value: apply -k $(workspaces.source.path)/demo/app/k8s/overlays/dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-bot-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: build-bot
