apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl
spec:
  workspaces:
    - name: source
  params:
    - name: COMMAND
  steps:
    - name: kubectl
      image: quay.io/karpenter/kubectl
      script: |
        kubectl $(params.COMMAND)
