apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
    - name: TLS_VERIFY
    - name: CONTEXT_PATH
      default: .
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/karpenter/buildah
      workingdir: $(workspaces.source.path)
      script: |        
        buildah bud --no-cache --tls-verify=$(params.TLS_VERIFY) -f $(params.CONTEXT_PATH)/Dockerfile -t $(params.IMAGE) $(params.CONTEXT_PATH)
      volumeMounts:
        - name: containers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: push
      image: quay.io/karpenter/buildah
      workingdir: $(workspaces.source.path)
      script: |
        buildah push --tls-verify=$(params.TLS_VERIFY) $(params.IMAGE)
      volumeMounts:
        - name: containers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: containers
      emptyDir: {}
